# Generated by Django 4.1 on 2023-11-30 21:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_images/'),
        ),
    ]
