# Generated by Django 4.1 on 2023-12-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='waiting', max_length=10),
        ),
    ]
